parameters:
    twitch.client_id: '%env(TWITCH_CLIENT_ID)%'
    twitch.client_secret: '%env(TWITCH_CLIENT_SECRET)%'
    twitch.broadcaster_id: '%env(TWITCH_BROADCASTER_ID)%'
    twitch.username: '%env(TWITCH_USERNAME)%'
    twitch.channel: '%env(TWITCH_CHANNEL)%'
    twitch.connect_message: '[GLOBOT] Connected to Globnot channel!'
    twitch.connect_message_repeat: 1