vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        satisfactory_bp:
            uri_prefix: /uploads/satisfactory_bp
            upload_destination: '%kernel.project_dir%/public/uploads/satisfactory_bp'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_update: true
            delete_on_remove: true

        satisfactory_sbp:
            uri_prefix: /uploads/satisfactory_sbp
            upload_destination: '%kernel.project_dir%/public/uploads/satisfactory_sbp'
            namer: App\Infrastructure\Namer\Site\SatisfactorySbpNamer
            delete_on_update: true
            delete_on_remove: true

        satisfactory_sbpcfg:
            uri_prefix: /uploads/satisfactory_sbpcfg
            upload_destination: '%kernel.project_dir%/public/uploads/satisfactory_sbpcfg'
            namer: App\Infrastructure\Namer\Site\SatisfactorySbpcfgNamer
            delete_on_update: true
            delete_on_remove: true