name: app

type: php:8.3

dependencies:
    php:
        composer/composer: "^2"

runtime:
    extensions:
        - apcu
        - blackfire
        - mbstring
        - pdo_pgsql
        - sodium
        - xsl

variables:
    php:
        opcache.preload: config/preload.php
# Variables d'environnement par défaut (pour la branche dev par exemple)
    env:
        APP_ENV: "dev"
        APP_DEBUG: "true"

# Configuration pour la branche production (main)
# Cette section est évaluée seulement si l'environnement est "production"
environments:
    main:
        variables:
            env:
                APP_ENV: "prod"
                APP_DEBUG: "false"

build:
    flavor: none

disk: 1024

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"

mounts:
    "/var": { source: local, source_path: var }
    "/data": { source: local, source_path: "data" }
    "/public/uploads": { source: local, source_path: "uploads" }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | bash

        NODE_VERSION=20 symfony-build

    deploy: |
        set -x -e

        symfony-deploy

relationships:
    database: "db:postgresql"

crons:
    security-check:
        # Check that no security issues have been found for PHP packages deployed in production
        # See https://github.com/fabpot/local-php-security-checker
        spec: "50 23 * * *"
        cmd: if [ "$PLATFORM_ENVIRONMENT_TYPE" = "production" ]; then croncape php-security-checker; fi
    app_update_trackers:
        spec: "*/5 * * * *"
        cmd: "php bin/console app:update-trackers"
