# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twitch.client_id: '%env(TWITCH_CLIENT_ID)%'
    twitch.client_secret: '%env(TWITCH_CLIENT_SECRET)%'
    twitch.broadcaster_id: '%env(TWITCH_BROADCASTER_ID)%'
    twitch.username: '%env(TWITCH_USERNAME)%'
    twitch.channel: '%env(TWITCH_CHANNEL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

# Service

    App\Infrastructure\Client\Twitch\TwitchApiClient:
        arguments:
            $clientId: '%twitch.client_id%'
            $clientSecret: '%twitch.client_secret%'

    App\Infrastructure\Service\Twitch\TwitchGetSubscriberCountService:
        arguments:
            $clientId: '%twitch.client_id%'
            $broadcasterId: '%twitch.broadcaster_id%'

# Interface

    App\Application\Interface\Twitch\TwitchApiInterface:
        alias: App\Infrastructure\Client\Twitch\TwitchApiClient

    App\Application\Interface\Twitch\TwitchSubscriberInterface:
        alias: App\Infrastructure\Service\Twitch\TwitchSubscriberService

    App\Application\Interface\Twitch\TwitchAccessTokenInterface:
        alias: App\Infrastructure\Service\Twitch\TwitchAccessTokenService

# VichUploader Namer
    App\Infrastructure\Namer\Site\SatisfactorySbpNamer:
        public: true
        tags:
            - { name: vich_uploader.namer, mapping: your_entity_mapping }

    App\Infrastructure\Namer\Site\SatisfactorySbpcfgNamer:
        public: true
        tags:
            - { name: vich_uploader.namer, mapping: your_entity_mapping }